Jiwoon
HSU-Likelion-Backend-12th/team-1 pull request #6
Opened 2024-04-09 07:54 UTC by Hjwoon

### ✨ 이슈 번호

- #1 - 지난 과제를 불러오는 부분에 대해 제가 이해가 부족한 것 같습니다. 제가 이번주 과제가 테스트 실행이 다 안됐는데 인텔리제이가 이 파일을 실행 파일로 인식을 못하는 것 같습니다... 맨 처음 제 브랜치에서 git pull하여 파일을 받아오고 다운받은 소스 파일을 폴더째 복사 붙여넣기 하여 인텔리제이에서 작성했는데 디스코드 질문방에 올린대로 오류가 났습니다. 정말 다양한 방법을 사용해보았는데도 해결이 안돼 혹시 어떻게 해야하는지 알려주시면 감사하겠습니다:) 혹은 2주차 과제 맨 처음 시작할 때 환경을 세팅하는 방법에 대해 좀더 자세히 알려주시면 다시 한번 따라서 실습해보겠습니다!

<br><br>

### 📄 과제를 통해 배운 것

- 싱글톤에 대해 배웠습니다. 코드를 작성하며 따라할 때 매번 new 하면 새로운 객체가 그때그때 계속 생기지 않을까 하는 의문이 들었는데 2-3-2 영상에서 싱글톤에 대한 내용을 학습하여 매번 객체를 생성하지 않고 한번 생성한 객체를 계속 불러올 수 있다는 궁금했던 내용이 해소되었습니다. 

- 과제를 통해 배운 것을 작성해주세요.
- 블로그 링크 첨부, PDF 파일 멘토에게 전달, 간단한 텍스트로 작성 등 아무거나 괜찮습니다! 😊

<br><br>

### 🦁 이번 주 과제는 어땠나요?

#### 1-1) 어려웠던 점이 있다면 작성해주세요! 없다면 쓰지 않아도 됩니다.

<br>

#### 1-2) 어떻게 극복했나요?
- 

<br>

#### 2) 과제 난이도는 어느 정도였나요?
- ⭐️⭐️⭐️ (1: 너무 쉽다, 3: 보통이다, 5: 너무 어렵다)

<br>

#### 3) 이번 주 세션/과제에서의 개선사항을 작성해주세요! 없다면 쓰지 않아도 됩니다.
-

2024-04-10 04:08 UTC, MinseoKangQ commented
헉!! 제가 제가 따로 한번 봐드릴게요!! 🥲🥲

2024-04-10 05:50 UTC, MinseoKangQ requested changes
`singleton` 패키지를 `src/main`이 아닌, `src/test` 내부로 이동해주세요!

2024-04-10 05:50 UTC, MinseoKangQ commented on jiwoon/hw2/spring-core-basic/src/main/java/spring/springcorebasic/singleton/SingletonService.java
이 클래스는 `src/main/singleton` 패키지가 아니라, `src/test/singleton` 패키지에 존재해야 합니다!

2024-04-10 05:50 UTC, MinseoKangQ commented on jiwoon/hw2/spring-core-basic/src/main/java/spring/springcorebasic/singleton/SingletonTest.java
이 클래스 또한 `src/main/singleton` 패키지가 아니라, `src/test/singleton` 패키지에 존재해야 합니다!

2024-04-10 05:50 UTC, MinseoKangQ commented on jiwoon/hw2/spring-core-basic/src/main/java/spring/springcorebasic/singleton/SingletonService.java
<img width="428" alt="스크린샷 2024-04-10 오후 2 49 15" src="https://github.com/HSU-Likelion-Backend-12th/team-1/assets/98332877/041c909e-534f-4d6b-953e-f79df59d1ae2">

2024-04-11 03:28 UTC, Hjwoon commented on jiwoon/hw2/spring-core-basic/src/main/java/spring/springcorebasic/singleton/SingletonTest.java
넵 파일 위치 수정은 완료했습니다!

2024-04-11 13:06 UTC, MinseoKangQ approved these changes

2024-04-11 13:07 UTC, MinseoKangQ commented
과제 하느라 고생 많았어요!! 😀😀👍👍

2024-04-11 13:07 UTC, merged